# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

K1_D_nu <- function(k, D, Q, dim, C, Y, jj, nu = 0L) {
    .Call(`_tensorMiss_K1_D_nu`, k, D, Q, dim, C, Y, jj, nu)
}

K1_Ft_est <- function(x, A1) {
    .Call(`_tensorMiss_K1_Ft_est`, x, A1)
}

K1_cov_est <- function(x, dim, k) {
    .Call(`_tensorMiss_K1_cov_est`, x, dim, k)
}

K2_D_nu <- function(k, D, Q, dim, C, Y, jj, nu = 0L) {
    .Call(`_tensorMiss_K2_D_nu`, k, D, Q, dim, C, Y, jj, nu)
}

K2_Ft_est <- function(x, A1, A2) {
    .Call(`_tensorMiss_K2_Ft_est`, x, A1, A2)
}

K2_cov_est <- function(x, dim, k) {
    .Call(`_tensorMiss_K2_cov_est`, x, dim, k)
}

K3_D_nu <- function(k, D, Q, dim, C, Y, jj, nu = 0L) {
    .Call(`_tensorMiss_K3_D_nu`, k, D, Q, dim, C, Y, jj, nu)
}

K3_Ft_est <- function(x, A1, A2, A3) {
    .Call(`_tensorMiss_K3_Ft_est`, x, A1, A2, A3)
}

K3_cov_est <- function(x, dim, k) {
    .Call(`_tensorMiss_K3_cov_est`, x, dim, k)
}

data_gen <- function(K, n, d, r, re, eta, coef_f, coef_fe, coef_e, heavy_tailed = FALSE, t_df = 3L, seed = 2023L) {
    .Call(`_tensorMiss_data_gen`, K, n, d, r, re, eta, coef_f, coef_fe, coef_e, heavy_tailed, t_df, seed)
}

partition_MSE <- function(x1, x2, par_num = 100L) {
    .Call(`_tensorMiss_partition_MSE`, x1, x2, par_num)
}

